#!/bin/bash

# Author:   Ronny Biemann
#           Copyright 2016
# File:     xcompress
# License:  GPL-3.0

set -e
source xbase

declare -r program_name=${0##*/}

# Configure filetype-driver
declare -r _gzip=$(find_program_like pigz gzip)
declare -r _bzip=$(find_program_like bzip2)
declare -r _xz=$(find_program_like xz)
declare -r _lzma=$(find_program_like lzma)

declare -a available_drivers=("plain")
[ -x "${_bzip}" ] && available_drivers+=("bzip2")
[ -x "${_gzip}" ] && available_drivers+=("gzip")
[ -x "${_lzma}" ] && available_drivers+=("lzma")
[ -x "${_xz}" ] && available_drivers+=("xz")

# Parse command line arguments and feed parsed arguments
declare -r args=$(getopt --options=h --longoptions=help,driver --name="${program_name}" -- "$@")
eval set -- "${args}"

# Parse arguments
while true; do
  case ${1} in
  --driver) # Print installed drivers
    echo "plain --> $(which cat)"
    [ -x "${_bzip}" ] && echo "bzip --> ${_bzip}"
    [ -x "${_gzip}" ] && echo "gzip --> ${_gzip}"
    [ -x "${_lzma}" ] && echo "lzma --> ${_lzma}"
    [ -x "${_xz}" ] && echo "xz --> ${_xz}"
    shift
    exit 0
    ;;

  -h|--help)  # Print help message
    cat << EOF
Usage: ${program_name} [OPT] FILE

Compress data from stdin into FILE. This works like default shell redirection, except
that ${program_name} automatically detects filetypes by their filename
extension and applies an appropriate compression driver. Driver-specific
options may be passed through environment variables like XCOMPRESS_<DRIVER_FLAGS.
E.g for plain files (typically the driver is cat(1)):
  XCOMPRESS_PLAIN_FLAGS=--number ${program_name} FILE

Available flags for OPT:
  --driver
    List installed drivers

  -h, --help
    $(help_help_message)
EOF
    shift
    exit 0
    ;;

  --)
    shift
    break
    ;;
  esac
done

# Check if filename is valid
file=${1:?Invalid FILE}

# Extract fileextension (lower-case)
filetype=$(tr '[[:upper:]]' '[[:lower:]]' <<< ${file##*.})

# Filetype specific behaviour
case "${filetype}" in
gz|gzip)
  [ ! -x "${_gzip}" ] && die -1 "No driver for ${filetype} files!"
  ${_gzip} -c ${XCOMPRESS_GZIP_FLAGS} > "${file}"
  ;;

bz2|bzip2)
  [ ! -x "${_bzip}" ] && die -1 "No driver for ${filetype} files!"
  ${_bzip} -c ${XCOMPRESS_BZIP_FLAGS} > "${file}"
  ;;

xz)
  [ ! -x "${_xz}" ] && die -1 "No driver for ${filetype} files!"
  ${_xz} -c ${XCOMPRESS_XZ_FLAGS} > "${file}"
  ;;

lzma)
  [ ! -x "${_lzma}" ] && die -1 "No driver for ${filetype} files!"
  ${_lzma} -c ${XCOMPRESS_LZMA_FLAGS} > "${file}"
  ;;

*)
  cat ${XCOMPRESS_PLAIN_FLAGS} > "${file}"
  ;;
esac

# Report success to shell
exit 0
