#!/bin/sh

# Parse command line arguments and feed parsed arguments
args=$(getopt -o dhi:r:su -l delete,help,insert:,replace:,skip,unique -n ${0##*/} -- "$@")
eval set -- "$args"

# Parse arguments
while true; do
  case $1 in
    -i|--insert)
      # Insert new header as first line
      insert_header=$2
      shift 2
      ;;

    -r|--replace)
      # Replace current header
      replace_header=$2
      shift 2
      ;;

    -d|--delete)
      # Delete current header
      delete_header=1
      shift
      ;;

    -s|--skip)
      # Print current header but don't print data
      skip_data=1
      shift
      ;;

    -u|--unique)
      # Remove repeated headers
      unique_header=1
      shift
      ;;

    -h|--help)
      cat << EOF
  -i|--insert STR   Insert STR as header
  -r|--replace STR  Replace STR as header
  -d|--delete       Delete header
  -s|--skip         Skip data
  -u|--unique       Remove repeated header definitions
  -h|--help         Print this message and terminate
EOF
      exit 0
      ;;

    --)
      shift
      break
      ;;
  esac
done

# Insert header
if [ x"" != x$insert_header ]; then
  raw_header=$insert_header
else
  # Consume exsiting header
  IFS= read -r raw_header
fi

# Replace header
if [ x"" != x$replace_header ]; then
  raw_header=$replace_header
fi

# Delete header
if [ 0 != ${delete_header:-0} ]; then
  raw_header=""
fi

if [ 0 == ${delete_header:-0} ]; then
  echo $raw_header
fi

# Skip remaining data
if [ 0 == ${skip_data:-0} ]; then
  if [ 0 == ${unique_header:-0} ]; then cat
  else fgrep -v "$raw_header"
  fi
fi
